#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/lib";
use TDone;
use TDone::TUI;

eval { TDone::TUI::cmd_ui(@ARGV) };
if ($@) { chomp(my $err = $@); die "tdone_ui: $err\n" }
